package org.tokenmanager;

import java.net.URI;
import java.time.Clock;
import java.time.Duration;
import java.util.Collections;
import java.util.Set;
import java.util.function.Supplier;
import lombok.Builder;
import lombok.Builder.Default;
import lombok.NonNull;
import lombok.ToString;
import lombok.Value;
import okhttp3.OkHttpClient;

@Value
@Builder
@ToString(exclude = {
    "clientSecretSupplier", "password", "authorizationCode",
    "codeVerifier", "refreshToken", "assertionSupplier"
})
public class TokenConfig {

  // Timeout for individual HTTP operations
  private static final Duration DEFAULT_HTTP_TIMEOUT = Duration.ofSeconds(10);
  // How long before token expiry should we refresh
  private static final Duration DEFAULT_REFRESH_THRESHOLD = Duration.ofSeconds(30);

  @NonNull String tokenEndpoint;
  @NonNull String clientId;
  @NonNull Supplier<String> clientSecretSupplier;

  @NonNull @Default OAuth2GrantType grantType = OAuth2GrantType.CLIENT_CREDENTIALS;

  @NonNull @Default Set<String> scope = Collections.emptySet();

  @NonNull @Default Duration refreshThreshold = DEFAULT_REFRESH_THRESHOLD;

  @NonNull @Default Duration httpTimeout = DEFAULT_HTTP_TIMEOUT;

  @NonNull @Default Clock clock = Clock.systemUTC();

  @NonNull @Default ClientAuthMethod clientAuthMethod = ClientAuthMethod.CLIENT_SECRET_POST;

  @Default int maxRetryAttempts = 3;
  @NonNull @Default Duration initialRetryDelay = Duration.ofSeconds(1);
  /**
   * Minimum number of calls before the circuit breaker evaluates the failure rate.
   * The failure rate threshold is fixed at 100%, so the circuit breaker opens
   * after {@code circuitBreakerMinimumCalls} consecutive failures (i.e., every call
   * in the sliding window must fail).
   */
  @Default int circuitBreakerMinimumCalls = 3;
  @NonNull @Default Duration circuitBreakerWaitDuration = Duration.ofSeconds(60);

  @Default boolean eagerFetch = false;

  // Fields for other grant types
  String username; // For password grant
  String password;
  String authorizationCode; // For authorization_code grant
  String redirectUri;
  String codeVerifier; // PKCE (optional)
  String refreshToken; // For refresh_token grant
  Supplier<String> assertionSupplier; // For JWT_BEARER

  // Optional custom HTTP client (typically for testing)
  OkHttpClient httpClient;

  /**
   * Partial builder — Lombok merges these methods with the generated ones.
   * {@code clientSecretSupplier(Supplier<String>)} and {@code assertionSupplier(Supplier<String>)}
   * are still auto-generated by Lombok since they are not defined here.
   */
  public static class TokenConfigBuilder {
    public TokenConfigBuilder clientSecret(@NonNull String secret) {
      this.clientSecretSupplier = () -> secret;
      return this;
    }

    public TokenConfigBuilder assertion(@NonNull String assertion) {
      this.assertionSupplier = () -> assertion;
      return this;
    }
  }

  /** Invokes the supplier on each call — secrets are always fresh. */
  public String getClientSecret() {
    return clientSecretSupplier.get();
  }

  /** Invokes the supplier on each call, or returns null if no assertion was configured. */
  public String getAssertion() {
    return assertionSupplier != null ? assertionSupplier.get() : null;
  }

  public void validate() {
    if (refreshThreshold.isNegative() || refreshThreshold.isZero()) {
      throw new IllegalArgumentException("refreshThreshold must be positive");
    }
    if (httpTimeout.isNegative() || httpTimeout.isZero()) {
      throw new IllegalArgumentException("httpTimeout must be positive");
    }
    if (maxRetryAttempts < 1) {
      throw new IllegalArgumentException("maxRetryAttempts must be >= 1");
    }
    if (initialRetryDelay.isNegative() || initialRetryDelay.isZero()) {
      throw new IllegalArgumentException("initialRetryDelay must be positive");
    }
    if (circuitBreakerMinimumCalls < 1) {
      throw new IllegalArgumentException("circuitBreakerMinimumCalls must be >= 1");
    }
    if (circuitBreakerWaitDuration.isNegative() || circuitBreakerWaitDuration.isZero()) {
      throw new IllegalArgumentException("circuitBreakerWaitDuration must be positive");
    }
    URI uri = URI.create(tokenEndpoint);
    if (!"https".equalsIgnoreCase(uri.getScheme())) {
      throw new IllegalArgumentException("tokenEndpoint must use HTTPS");
    }

    // Validate based on grant type
    switch (grantType) {
      case PASSWORD -> {
        if (username == null || password == null) {
          throw new IllegalArgumentException("Password grant requires username and password");
        }
      }
      case AUTHORIZATION_CODE -> {
        if (authorizationCode == null || redirectUri == null) {
          throw new IllegalArgumentException(
              "Authorization code grant requires code and redirect URI");
        }
      }
      case REFRESH_TOKEN -> {
        if (refreshToken == null) {
          throw new IllegalArgumentException("Refresh token grant requires refresh token");
        }
      }
      case JWT_BEARER -> {
        if (assertionSupplier == null) {
          throw new IllegalArgumentException("JWT Bearer grant requires assertion");
        }
      }
      case IMPLICIT ->
          throw new IllegalArgumentException(
              "Implicit grant type is not supported by token endpoint");
      case CLIENT_CREDENTIALS -> {
        /* already validated by @NonNull fields */
      }
    }
  }

  String getScopeString() {
    return scope.isEmpty() ? "" : String.join(" ", scope);
  }
}
